var listMovies = ["https://m.media-amazon.com/images/M/MV5BNTU0NmE3M2UtNGM0Yi00NjZhLTk1MDAtZWY1ODYzNWUyMGM2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BZmYzMzU4NjctNDI0Mi00MGExLWI3ZDQtYzQzYThmYzc2ZmNjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMTMzOTk1MzIyN15BMl5BanBnXkFtZTcwNTM3MjczMQ@@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BZGMxZTdjZmYtMmE2Ni00ZTdkLWI5NTgtNjlmMjBiNzU2MmI5XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg" ,
"https://m.media-amazon.com/images/M/MV5BNzA5ZDNlZWMtM2NhNS00NDJjLTk4NDItYTRmY2EwMWZlMTY3XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg", "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMjE2NDkxNTY2M15BMl5BanBnXkFtZTgwMDc2NzE0MTI@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMDg2YzI0ODctYjliMy00NTU0LTkxODYtYTNkNjQwMzVmOTcxXkEyXkFqcGdeQXVyNjg2NjQwMDQ@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BYjI3NDg0ZTEtMDEwYS00YWMyLThjYjktMTNlM2NmYjc1OGRiXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_UX182_CR0,0,182,268_AL_.jpg" ,
"https://m.media-amazon.com/images/M/MV5BYWVhZjZkYTItOGIwYS00NmRkLWJlYjctMWM0ZjFmMDU4ZjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BYzE5MjY1ZDgtMTkyNC00MTMyLThhMjAtZGI5OTE1NzFlZGJjXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BNjk1Njk3YjctMmMyYS00Y2I4LThhMzktN2U0MTMyZTFlYWQ5XkEyXkFqcGdeQXVyODM2ODEzMDA@._V1_UY268_CR43,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMjEzMzEzNjg0N15BMl5BanBnXkFtZTcwMzg4NDk0Ng@@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMTQ2NjE4NDE2NV5BMl5BanBnXkFtZTgwOTcwNDE5NzE@._V1_UX182_CR0,0,182,268_AL_.jpg" , 
"https://m.media-amazon.com/images/M/MV5BNzlkNzVjMDMtOTdhZC00MGE1LTkxODctMzFmMjkwZmMxZjFhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMzExYjcyYWMtY2JkOC00NDUwLTg2OTgtMDI3MGY2OWQzMDE2XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMTQ2NTMxODEyNV5BMl5BanBnXkFtZTcwMDgxMjA0MQ@@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BYjQ1ZTMxNzgtZDcxOC00NWY5LTk3ZjAtYzRhMDhlNDZlOWEzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMTUxNTk5MTE0OF5BMl5BanBnXkFtZTcwMjA2NzY3NA@@._V1_UX182_CR0,0,182,268_AL_.jpg" , 
"https://m.media-amazon.com/images/M/MV5BMTM3NTg2NDQzOF5BMl5BanBnXkFtZTcwNjc2NzQzOQ@@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMTQxOTA2NDUzOV5BMl5BanBnXkFtZTgwNzY2MTMxMzE@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BMjMxODI2NDM5Nl5BMl5BanBnXkFtZTgwNjgzOTk1MTI@._V1_UX182_CR0,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BOTIzYmUyMmEtMWQzNC00YzExLTk3MzYtZTUzYjMyMmRiYzIwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_UY268_CR1,0,182,268_AL_.jpg" , "https://m.media-amazon.com/images/M/MV5BZDZlMjc0MTItZWY2YS00ZDJhLWI2M2MtODVjNWFmYTQxYmJjXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_UX182_CR0,0,182,268_AL_.jpg"]

var namesMovies = ["Mortal Kombat", "Godzilla vs. Kong" , "Ponte para Terabítia" , "O senhor dos Anéis: A Sociedade do Anel" , "O Senhor dos Anéis: As Duas Torres " , " O Senhor dos Anéis: O Retorno do Rei" , " John Wick: De volta ao jogo" , "John Wick: Um Novo Dia para Matar" , "John Wick: Parabellum" , "Liga da Justiça de Zack Snyder (2021)" , "Liga da Justiça (2017)" , "Deadpool" , "Deadpool 2" , "Gigantes de aço" , "Como eu Era Antes de Você" , "Velozes e Furiosos" , "Velozes e Furiosos 2" , "Velozes e Furiosos 3: Desafio em Tóquio" , "Velozes & Furiosos 4" , "Velozes & Furiosos 5: Operaçao Rio" , "Velozes & Furiosos 6" , "Velozes & Furiosos 7" , "Velozes & Furiosos 8" , 
"Velozes & Furiosos: Hobbs & Shaw" , "Velozes & Furiosos 9"]

var trailersLinks =["https://www.youtube.com/watch?v=8Tk8sqXlogM" , "https://www.youtube.com/watch?v=ZQA-Bg9MydE" , "https://www.youtube.com/watch?v=ZJI9ATHufLg" , "https://www.youtube.com/watch?v=0i86oM1nHjM" ,"https://www.youtube.com/watch?v=8uwJoAj3gt8" , "https://www.youtube.com/watch?v=cEknWmwZaXk" , "https://www.youtube.com/watch?v=rUKOAwlyNag" , "https://www.youtube.com/watch?v=AyaD8KTKln4", "https://www.youtube.com/watch?v=PP0cnmZPbws" , "https://www.youtube.com/watch?v=BifA90UAQtg" , "https://www.youtube.com/watch?v=A9woJbIXxyE" , "https://www.youtube.com/watch?v=Q9X-bAE8KTc" , "https://www.youtube.com/watch?v=1P9OzWX6nzE" , "https://www.youtube.com/watch?v=B33mhvSDO3c" , "https://www.youtube.com/watch?v=PnqUs3xiAVI" , "https://www.youtube.com/watch?v=ZuQ-CWAjFT4" , 
"https://www.youtube.com/watch?v=ONs4_PtakGc" , "https://www.youtube.com/watch?v=HVQWZkd8cDk" , "https://www.youtube.com/watch?v=yAr404wj--Y" , "https://www.youtube.com/watch?v=2SbJCKTX87U&t=4s" , "https://www.youtube.com/watch?v=KkzzyAUJqkY" , "https://www.youtube.com/watch?v=hujU0dw6Erk" , "https://www.youtube.com/watch?v=KvSlvtPnZTo" , "https://www.youtube.com/watch?v=CzawIsb4X2Q" , "https://www.youtube.com/watch?v=JklfACQV6Zs"]

for (i = 0 ; i < listMovies.length ; i ++ ){
    document.write('<div class="catalog">' + '<a href= "' + trailersLinks [i] + '"' + 'target="_blank">' + '<img src =' + listMovies[i] + '>' + '</a>' + '<span class="title">' + namesMovies[i] + '</span>' + '</div>')    
}